## Switches
set_property PACKAGE_PIN V17 [get_ports {dir}]
set_property IOSTANDARD LVCMOS33 [get_ports {dir}]

set_property PACKAGE_PIN V16 [get_ports {cmd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmd[0]}]
set_property PACKAGE_PIN W16 [get_ports {cmd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmd[1]}]

set_property PACKAGE_PIN W17 [get_ports {din[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {din[0]}]
set_property PACKAGE_PIN W15 [get_ports {din[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {din[1]}]
set_property PACKAGE_PIN V15 [get_ports {din[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {din[2]}]
set_property PACKAGE_PIN W14 [get_ports {din[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {din[3]}]
set_property PACKAGE_PIN W13 [get_ports {din[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {din[4]}]
set_property PACKAGE_PIN V2 [get_ports {din[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {din[5]}]
#set_property PACKAGE_PIN T3 [get_ports {sw[9]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw[9]}]
#set_property PACKAGE_PIN T2 [get_ports {sw[10]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw[10]}]
#set_property PACKAGE_PIN R3 [get_ports {sw[11]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw[11]}]
#set_property PACKAGE_PIN W2 [get_ports {sw[12]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw[12]}]
#set_property PACKAGE_PIN U1 [get_ports {sw[13]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw[13]}]
#set_property PACKAGE_PIN T1 [get_ports {sw[14]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw[14]}]
#set_property PACKAGE_PIN R2 [get_ports {sw[15]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw[15]}]

## LEDs
set_property PACKAGE_PIN U16 [get_ports {dout_din[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout_din[0]}]
set_property PACKAGE_PIN E19 [get_ports {dout_din[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout_din[1]}]
set_property PACKAGE_PIN U19 [get_ports {dout_din[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout_din[2]}]
set_property PACKAGE_PIN V19 [get_ports {dout_din[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout_din[3]}]
set_property PACKAGE_PIN W18 [get_ports {dout_din[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout_din[4]}]
set_property PACKAGE_PIN U15 [get_ports {dout_din[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout_din[5]}]

set_property PACKAGE_PIN U14 [get_ports {dout_shifted[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout_shifted[0]}]
set_property PACKAGE_PIN V14 [get_ports {dout_shifted[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout_shifted[1]}]
set_property PACKAGE_PIN V13 [get_ports {dout_shifted[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout_shifted[2]}]
set_property PACKAGE_PIN V3 [get_ports {dout_shifted[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout_shifted[3]}]
set_property PACKAGE_PIN W3 [get_ports {dout_shifted[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout_shifted[4]}]
set_property PACKAGE_PIN U3 [get_ports {dout_shifted[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout_shifted[5]}]